#!/usr/bin/env node
/**
 * npm run setup
 *
 * Reads .env and profile/*.json, bakes the profile into the Code nodes, builds
 * the two importable workflows, and tells you exactly what is still missing.
 *
 * Safe to run as many times as you like — it only writes generated files.
 * No secret is ever written to disk here: API keys stay in .env and are read
 * at runtime through the container's environment.
 */
import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync, copyFileSync } from 'node:fs';
import path from 'node:path';
import { ROOT, c, ok, bad, warn, info, head, loadEnv, readJson, providerOf } from './env.mjs';

const CODE_DIR = path.join(ROOT, 'n8n', 'code');
const TPL_DIR = path.join(ROOT, 'n8n', 'workflows');
const OUT_DIR = path.join(ROOT, 'n8n', 'dist');

let problems = 0;
const fail = (m) => { bad(m); problems++; };

console.log(`\n${c.bold}Job Agent setup${c.reset}`);

// ---------------------------------------------------------------------------
// 1. .env
// ---------------------------------------------------------------------------
head('1. Reading .env');

if (!existsSync(path.join(ROOT, '.env'))) {
  copyFileSync(path.join(ROOT, '.env.example'), path.join(ROOT, '.env'));
  warn('No .env found, so one was created from .env.example.');
  info('Open .env, fill it in, then run this again.');
  console.log(`\n  ${c.blue}notepad .env${c.reset}   (or open it in your editor)\n`);
  process.exit(1);
}

const env = loadEnv();
ok('.env found');

const provider = providerOf(env);
if (!provider.key) {
  fail(`LLM_PROVIDER="${env.LLM_PROVIDER}" is not one of: anthropic, openai, gemini`);
} else {
  ok(`AI provider: ${provider.label}`);
  if (!env[provider.key]) {
    fail(`${provider.key} is empty in .env — ${provider.label} needs it`);
  } else {
    ok(`${provider.key} is set`);
  }
  const model = env[provider.modelVar] || provider.defaultModel;
  info(`model: ${model}${env[provider.modelVar] ? '' : ' (default)'}`);
}

for (const [key, why] of [
  ['GOOGLE_SHEET_ID', 'the spreadsheet the pipeline writes to'],
  ['APPLY_TOKEN', 'the shared password between n8n and the browser service'],
]) {
  if (!env[key]) fail(`${key} is empty in .env — needed for ${why}`);
  else ok(`${key} is set`);
}

if (env.APPLY_TOKEN && env.APPLY_TOKEN.length < 16) {
  warn('APPLY_TOKEN is short. Any long random string works; longer is better.');
}

// ---------------------------------------------------------------------------
// 2. profile files
// ---------------------------------------------------------------------------
head('2. Reading your profile');

function loadProfileFile(name) {
  const live = path.join(ROOT, 'profile', `${name}.json`);
  const example = path.join(ROOT, 'profile', `${name}.example.json`);
  if (!existsSync(live)) {
    copyFileSync(example, live);
    warn(`profile/${name}.json did not exist, so a copy of the example was made.`);
    info(`Edit profile/${name}.json with your real details.`);
    problems++;
  }
  return readJson(live);
}

let profile, masterResume;
try {
  profile = loadProfileFile('profile');
  masterResume = loadProfileFile('master-resume');
} catch (e) {
  fail(e.message);
  console.log(`\n${c.red}Fix the file above and run setup again.${c.reset}\n`);
  process.exit(1);
}

// Drop the _readme keys so they never reach a prompt.
const clean = (o) => Object.fromEntries(Object.entries(o).filter(([k]) => !k.startsWith('_')));
profile = clean(profile);
masterResume = clean(masterResume);

if (!profile.name || profile.name === 'Your Name') {
  fail('profile/profile.json still says "Your Name" — put your real details in it');
} else {
  ok(`profile: ${profile.name}, ${profile.current_title || 'no title set'}`);
}

if (!masterResume.experience?.length) {
  warn('profile/master-resume.json has no experience entries — resumes will be thin');
} else {
  const bullets = masterResume.experience.reduce((n, j) => n + (j.bullets?.length || 0), 0);
  ok(`master resume: ${masterResume.experience.length} role(s), ${bullets} bullet(s)`);
}

const filters = profile.filters || {};
if (!filters.title_allowlist?.length) {
  warn('No filters.title_allowlist — every job title will reach the AI, which costs more');
} else {
  ok(`filters: ${filters.title_allowlist.length} allowed title words, ` +
     `${(filters.title_blocklist || []).length} blocked`);
}

// ---------------------------------------------------------------------------
// 3. generate + build
// ---------------------------------------------------------------------------
head('3. Building the workflows');

const generated = `// GENERATED by "npm run setup" — do not edit.
// Source: profile/profile.json and profile/master-resume.json
// Contains no secrets. API keys are read from the environment at runtime.
const PROFILE = ${JSON.stringify(profile, null, 2)};
const MASTER_RESUME = ${JSON.stringify(masterResume, null, 2)};
`;
writeFileSync(path.join(CODE_DIR, '_profile.generated.js'), generated);
ok('baked your profile into the Code nodes');

const prelude = [
  readFileSync(path.join(CODE_DIR, '_profile.generated.js'), 'utf8'),
  readFileSync(path.join(CODE_DIR, 'lib.js'), 'utf8'),
].join('\n');

function loadCode(filename) {
  const body = readFileSync(path.join(CODE_DIR, filename), 'utf8');
  return `${prelude}\n// ---- ${filename} ----\n${body}`;
}

function inject(node) {
  if (node && typeof node === 'object') {
    for (const [key, value] of Object.entries(node)) {
      if (typeof value === 'string' && value.startsWith('@@include:')) {
        node[key] = loadCode(value.slice('@@include:'.length));
      } else {
        inject(value);
      }
    }
  }
  return node;
}

mkdirSync(OUT_DIR, { recursive: true });
for (const file of readdirSync(TPL_DIR).filter((f) => f.endsWith('.template.json'))) {
  const built = inject(JSON.parse(readFileSync(path.join(TPL_DIR, file), 'utf8')));
  const outName = file.replace('.template.json', '.json');
  writeFileSync(path.join(OUT_DIR, outName), JSON.stringify(built, null, 2));
  ok(`n8n/dist/${outName} — ${built.nodes.length} nodes`);
}

// ---------------------------------------------------------------------------
// 4. what's next
// ---------------------------------------------------------------------------
if (problems) {
  console.log(`\n${c.yellow}${c.bold}${problems} thing(s) still need you.${c.reset}`);
  console.log(`Fix them above, then run ${c.blue}npm run setup${c.reset} again.\n`);
  process.exit(1);
}

head('Ready. Next:');
console.log(`
  ${c.bold}1.${c.reset} Start everything
     ${c.blue}docker compose up -d${c.reset}
     Wait about a minute the first time — it downloads a browser.

  ${c.bold}2.${c.reset} Check it came up healthy
     ${c.blue}npm run doctor${c.reset}

  ${c.bold}3.${c.reset} Open n8n at ${c.blue}http://localhost:5678${c.reset} and:
       · Import both files from ${c.bold}n8n/dist/${c.reset}
         (Workflows → ⋯ → Import from File)
       · Connect Google Sheets, Gmail and Google Drive
         (Credentials → New → search for each → Sign in with Google)
       · Turn both workflows on

  ${c.bold}4.${c.reset} Set up your job monitors
     Follow ${c.bold}docs/distill-setup.md${c.reset} — that part cannot be automated,
     but it is copy-and-paste and takes about ten minutes.

  ${c.grey}Applications are OFF by default (DRY_RUN=true). The system will fill
  forms and screenshot them without submitting until you change that.${c.reset}
`);
